# Generated by Django 4.2.2 on 2023-06-25 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaseStoreApp', '0002_cart_order_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
