# Generated by Django 4.2.2 on 2023-06-27 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CaseStoreApp", "0004_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="CaseStoreApp.cart",
            ),
        ),
    ]
